export const allowedScopes = [
	"attachments:read",
	"custom_fields:read",
	"goals:read",
	"portfolios:read",
	"projects:read",
	"stories:read",
	"tags:read",
	"task_templates:read",
	"tasks:read",
	"tasks:write",
	"team_memberships:read",
	"teams:read",
	"users:read",
	"workspaces:read",
];
